from pywebdeb:latest

WORKDIR /tests

ADD /tests/end_to_end/test.sh /tests/test.sh
ADD /tests/end_to_end/app_test.py /tests/app_test.py
ADD requirements-dev.txt /tests/requirements-dev.txt
RUN pip3 install -r requirements-dev.txt

CMD ["bash", "test.sh"]
